# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
